version: "1"

services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8000:8000'
#    restart: on-failure
#    depends_on:
#      - postgres
#      - redis
#      - neo4j
#      - celery
#    volumes:
#      - .:/app
  neo4j:
    image: neo4j:4.4-community
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=$NEO4J_USER/$NEO4J_PASSWORD
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
      - ./neo4j/plugins:/plugins

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_NAME
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server" ]

  celery:
    container_name: celery
    env_file:
      - example.env
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run celery -A simple_social worker --loglevel=info
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - neo4j
      - postgres
      - redis
