# Generated by Django 4.2.6 on 2023-11-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postimage_uuid_alter_posttags_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
