# Generated by Django 4.2.4 on 2023-10-26 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_alter_friendrequest_action_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
