# Generated by Django 4.2.4 on 2023-10-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_alter_friendrequest_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='deleted_at',
        ),
    ]
