# Generated by Django 4.2.4 on 2023-10-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_remove_friendrequest_deleted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
