# Generated by Django 4.2.4 on 2023-10-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='unfriend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='unfriend_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
