# Generated by Django 4.2.4 on 2023-10-28 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0006_friendrequest_unfriend_friendrequest_unfriend_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
